// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqbevkdnikifahtlqueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxYmV2a2RuaWtpZmFodGxxdWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Mzg3NjAsImV4cCI6MjA2MTIxNDc2MH0.LZnjP-sFFg_3F-VrmbZyTuDiiyYPRHqa3XQOVAjTK9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);